spring:
  application:
    name: moein-antik-shop
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

server:
  port: 8080

jwt:
  secret: change-this-secret-before-production
  expiration-ms: 86400000

auth:
  otp:
    code-length: 6
    ttl: 2m
    resend-cooldown: 60s
    request-window: 15m
    max-requests-per-window: 5
    max-verify-attempts: 5
    dev-code: "123456"
    admin-phones:
      - "09155733360"

cache:
  key-prefix: moein-antik

springdoc:
  swagger-ui:
    path: /swagger-ui.html

payment:
  zarinpal:
    merchant-id: change-this-merchant-id
    request-url: https://api.zarinpal.com/pg/v4/payment/request.json
    verify-url: https://api.zarinpal.com/pg/v4/payment/verify.json
    start-pay-url: https://www.zarinpal.com/pg/StartPay
    callback-url: http://localhost:8080/api/payments/zarinpal/callback
    frontend-result-url: http://localhost:3000/payment/result
    currency: IRT
